version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000" 
    # depends_on:
    #   - db

#tu beda 2 kontenery (serwisy): db i web
# docker run --rm -v $PWD:/code -p 8000:8000 netg python manage.py runserver 0.0.0.0:8000
