# Generated by Django 3.2.5 on 2021-07-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_car', '0004_rename_car_rate_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car_id',
            new_name='car',
        ),
    ]
