# Generated by Django 3.2.5 on 2021-07-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_car.car'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(max_length=100),
        ),
    ]
