# Generated by Django 3.2.5 on 2021-07-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_car', '0006_rename_car_rate_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='rating',
        ),
    ]
